kind: pipeline
type: docker
name: duckment-ui

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    pull: if-not-exists

  - name: install
    image: node:10-alpine3.11
    pull: if-not-exists
    commands:
      - yarn

  - name: build
    image: node:10-alpine3.11
    pull: if-not-exists
    commands:
      - yarn build
    when:
      branch:
        - develop