kind: pipeline
type: docker
name: duckment-ui

workspace:
  path: /drone/src/${DRONE_REPO_NAME}

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    pull: if-not-exists
    privileged: true
    volumes:
      - name: git-cache
        path: /drone/src/${DRONE_REPO_NAME}/.git
    commands:
      - ls -a /root
      - cat /root/.netrc

  - name: install
    image: node:10-alpine3.11
    commands:
      - yarn

  - name: build
    image: node:10-alpine3.11
    commands:
      - yarn build
    when:
      branch:
        - develop

volumes:
  - name: git-cache
    host:
      path: /workspace/ci-volumes/git/${DRONE_REPO_NAME}/.git
  - name: gopath
    host:
      path: /workspace/ci-volumes/gopath
  - name: go-build-cache
    host:
      path: /workspace/ci-volumes/go_build_cache
  - name: node-modules
    host:
      path: /workspace/ci-volumes/node_modules/${DRONE_REPO_NAME}.${DRONE_BRANCH}
  - name: yarn-cache
    host:
      path: /workspace/ci-volumes/yarn-cache
  - name: netrc # for `go get go.zhuzi.me/go`
    host:
      path: /workspace/ci-volumes/netrc_ext
