kind: pipeline
type: docker
name: duckment-ui

steps:
  - name: install
    image: node:10-alpine3.11
    commands:
      - yarn

  - name: build
    image: node:10-alpine3.11
    commands:
      - yarn build
    when:
      branch:
        - develop